version: '3'

services:
  cyber:
    container_name: cyber
    image: At87668/Cyber:latest
    volumes:
      - ./.env:/app/apps/web/.env
      - ./public:/app/apps/web/public
    restart: always
    ports:
      - 2323:2323
